paths = [
  # dir is missing in snix's output
  "builtins/parseFlakeRef/eval-okay-parser-flake-ref",

  # Nix changed how filterSource works,
  # so the output of latest Nix and Snix differs
  #
  # Related issue: https://github.com/NixOS/nix/issues/7761
  "builtins/filterSource/symlink-dir",

  # Snix fails with duplicate attrs correctly,
  # but only with strict evaluation, while
  # Nix fails with lazy evaluation too
  "laziness/unthunked-dup-attr-path",

  # Nix fails, but Snix only emits a "UselessInherit" warning
  "scope/dup-inherit",

  # File and line differ
  "builtins/unsafeGetAttrPos/derivation",

  # Not implemented yet
  "builtins/unsafeGetAttrPos/foldl",
  "builtins/unsafeGetAttrPos/update",
  "builtins/unsafeGetAttrPos/listToAttrs",
  "builtins/unsafeGetAttrPos/corepkgs",
  "builtins/unsafeGetAttrPos/removeAttrs",
  "builtins/unsafeGetAttrPos/intersectAttrs",
  "builtins/unsafeGetAttrPos/eval-okay-inherit-attr-pos",
  "builtins/unsafeGetAttrPos/eval-okay-getattrpos-functionargs",

  # Line and column are evaluated eagerly
  "builtins/unsafeGetAttrPos/line-col-are-lazy",
]

builtins = ["readFile", "__nixPath"]

features = ["pipe-operators"]
