[nix_2_3]
paths = [
  # Ordering change after 2.3
  "xml/eval-okay-xml",

  # In 2.3, even if NIX_PATH is overwritten,
  # nix search path includes `corepkgs` and test
  # assertion fails
  "search_path/eval-okay-search-path",

  # Nix changed how filterSource works,
  # so the output of latest Nix and others (Nix2.3, Lix) differs
  #
  # Related issue: https://github.com/NixOS/nix/issues/7761
  "builtins/filterSource/symlink-dir",

  # getAttrPos gains support for functionArgs-returned sets after 2.3
  "builtins/unsafeGetAttrPos/eval-okay-getattrpos-functionargs",

  # getAttrPos calculates columns differently in 2.3
  "builtins/unsafeGetAttrPos/eval-okay-inherit-attr-pos",

  # Newer Nix versions return an attr set, while 2.3 returns null
  "builtins/unsafeGetAttrPos/corepkgs",

  # 2.3 returns the full /nix/store path
  "builtins/unsafeGetAttrPos/derivation",

  # Nix2.3 produces a path below:
  #   /nix/store/lc5bhdsagh8mrxkdbvdkmw9nv1vykavn-foo.drv
  "builtins/derivation/invalid-structured-attrs",

  # Nix still accepts this
  "builtins/derivation/json-key",

  # hash modulo broken in 2.3. It's broken in 2.3 and not a newly
  # introduced bug because there is now a similar test case in upstream
  "builtins/derivation/hash-modulo",

  # something changed in storePath behaviour between 2.3 and 2.30,
  # and it makes the same test failing in 2.3
  #
  # The likely change is https://github.com/NixOS/nix/commit/ea95327e72f5781295417b0eae46a5e351bebebd
  "builtins/storePath/path-with-subpath",
]
builtins = ["readFileType", "zipAttrsWith"]
features = ["flakes", "pipe-operators", "path-interpolation"]

[lix_latest]
paths = [
  "builtins/filterSource/symlink-dir",

  # Newer Nix versions return an attr set, while Lix returns null
  "builtins/unsafeGetAttrPos/corepkgs",

  # Returns null instead of attrset
  "builtins/unsafeGetAttrPos/derivation",

  # Lix produces a path below:
  #   /nix/store/lc5bhdsagh8mrxkdbvdkmw9nv1vykavn-foo.drv
  "builtins/derivation/invalid-structured-attrs",

  # Lix is more strict here and fails with
  # "unsupported input attribute 'foo' for the 'github' scheme"
  #
  # The change was initially introduced in https://gerrit.lix.systems/c/lix/+/1102
  # but later reverted are reapplied in https://git.lix.systems/lix-project/lix/commit/87fd1f024c7c979e5d96c41af4ef7e8bdb5792e1
  "builtins/parseFlakeRef/unknown-query-param",

  # something changed in storePath behaviour between 2.3 and 2.30,
  # and it makes the same test failing in 2.3
  #
  # The likely change is https://github.com/NixOS/nix/commit/ea95327e72f5781295417b0eae46a5e351bebebd
  "builtins/storePath/path-with-subpath",
]

[nix_latest]
paths = [
  # Nix still accepts this
  "builtins/derivation/json-key",
]
