// SPDX-License-Identifier: MIT
// Copyright © 2026 The Snix Project

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: snix/castore/protos/blobstore.proto

package castorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Describes more granular chunking information of a blob.
// More strict than BlobService's [StatBlobResponse],
// as it mixed request flags.
type BlobMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains a list of more granular chunks.
	// An empty list is only allowed if describing the empty blob.
	Chunks        []*BlobMeta_ChunkMeta `protobuf:"bytes,2,rep,name=chunks,proto3" json:"chunks,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobMeta) Reset() {
	*x = BlobMeta{}
	mi := &file_snix_castore_protos_blobstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobMeta) ProtoMessage() {}

func (x *BlobMeta) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_blobstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobMeta.ProtoReflect.Descriptor instead.
func (*BlobMeta) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_blobstore_proto_rawDescGZIP(), []int{0}
}

func (x *BlobMeta) GetChunks() []*BlobMeta_ChunkMeta {
	if x != nil {
		return x.Chunks
	}
	return nil
}

type BlobMeta_ChunkMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Digest of that specific chunk
	Digest []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Length of that chunk, in bytes.
	Size          uint64 `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BlobMeta_ChunkMeta) Reset() {
	*x = BlobMeta_ChunkMeta{}
	mi := &file_snix_castore_protos_blobstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BlobMeta_ChunkMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BlobMeta_ChunkMeta) ProtoMessage() {}

func (x *BlobMeta_ChunkMeta) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_blobstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BlobMeta_ChunkMeta.ProtoReflect.Descriptor instead.
func (*BlobMeta_ChunkMeta) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_blobstore_proto_rawDescGZIP(), []int{0, 0}
}

func (x *BlobMeta_ChunkMeta) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *BlobMeta_ChunkMeta) GetSize() uint64 {
	if x != nil {
		return x.Size
	}
	return 0
}

var File_snix_castore_protos_blobstore_proto protoreflect.FileDescriptor

const file_snix_castore_protos_blobstore_proto_rawDesc = "" +
	"\n" +
	"#snix/castore/protos/blobstore.proto\x12\x0fsnix.castore.v1\"\x80\x01\n" +
	"\bBlobMeta\x12;\n" +
	"\x06chunks\x18\x02 \x03(\v2#.snix.castore.v1.BlobMeta.ChunkMetaR\x06chunks\x1a7\n" +
	"\tChunkMeta\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x04R\x04sizeB\"Z snix.dev/castore/proto;castorev1b\x06proto3"

var (
	file_snix_castore_protos_blobstore_proto_rawDescOnce sync.Once
	file_snix_castore_protos_blobstore_proto_rawDescData []byte
)

func file_snix_castore_protos_blobstore_proto_rawDescGZIP() []byte {
	file_snix_castore_protos_blobstore_proto_rawDescOnce.Do(func() {
		file_snix_castore_protos_blobstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snix_castore_protos_blobstore_proto_rawDesc), len(file_snix_castore_protos_blobstore_proto_rawDesc)))
	})
	return file_snix_castore_protos_blobstore_proto_rawDescData
}

var file_snix_castore_protos_blobstore_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_snix_castore_protos_blobstore_proto_goTypes = []any{
	(*BlobMeta)(nil),           // 0: snix.castore.v1.BlobMeta
	(*BlobMeta_ChunkMeta)(nil), // 1: snix.castore.v1.BlobMeta.ChunkMeta
}
var file_snix_castore_protos_blobstore_proto_depIdxs = []int32{
	1, // 0: snix.castore.v1.BlobMeta.chunks:type_name -> snix.castore.v1.BlobMeta.ChunkMeta
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_snix_castore_protos_blobstore_proto_init() }
func file_snix_castore_protos_blobstore_proto_init() {
	if File_snix_castore_protos_blobstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snix_castore_protos_blobstore_proto_rawDesc), len(file_snix_castore_protos_blobstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_snix_castore_protos_blobstore_proto_goTypes,
		DependencyIndexes: file_snix_castore_protos_blobstore_proto_depIdxs,
		MessageInfos:      file_snix_castore_protos_blobstore_proto_msgTypes,
	}.Build()
	File_snix_castore_protos_blobstore_proto = out.File
	file_snix_castore_protos_blobstore_proto_goTypes = nil
	file_snix_castore_protos_blobstore_proto_depIdxs = nil
}
