// SPDX-License-Identifier: MIT
// Copyright © 2026 The Snix Project

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: snix/castore/protos/rpc_chunkstore.proto

package castorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type StatChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The blake3 digest of the chunk requested
	Digest        []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatChunkRequest) Reset() {
	*x = StatChunkRequest{}
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatChunkRequest) ProtoMessage() {}

func (x *StatChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatChunkRequest.ProtoReflect.Descriptor instead.
func (*StatChunkRequest) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_chunkstore_proto_rawDescGZIP(), []int{0}
}

func (x *StatChunkRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type StatChunkResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatChunkResponse) Reset() {
	*x = StatChunkResponse{}
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatChunkResponse) ProtoMessage() {}

func (x *StatChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatChunkResponse.ProtoReflect.Descriptor instead.
func (*StatChunkResponse) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_chunkstore_proto_rawDescGZIP(), []int{1}
}

type GetChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The blake3 digest of the chunk requested
	Digest        []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkRequest) Reset() {
	*x = GetChunkRequest{}
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkRequest) ProtoMessage() {}

func (x *GetChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkRequest.ProtoReflect.Descriptor instead.
func (*GetChunkRequest) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_chunkstore_proto_rawDescGZIP(), []int{2}
}

func (x *GetChunkRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type GetChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw chunk payload
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChunkResponse) Reset() {
	*x = GetChunkResponse{}
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChunkResponse) ProtoMessage() {}

func (x *GetChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChunkResponse.ProtoReflect.Descriptor instead.
func (*GetChunkResponse) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_chunkstore_proto_rawDescGZIP(), []int{3}
}

func (x *GetChunkResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutChunkRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Raw chunk payload
	Data          []byte `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkRequest) Reset() {
	*x = PutChunkRequest{}
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkRequest) ProtoMessage() {}

func (x *PutChunkRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkRequest.ProtoReflect.Descriptor instead.
func (*PutChunkRequest) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_chunkstore_proto_rawDescGZIP(), []int{4}
}

func (x *PutChunkRequest) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type PutChunkResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The blake3 digest of the chunk received
	Digest        []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutChunkResponse) Reset() {
	*x = PutChunkResponse{}
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutChunkResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutChunkResponse) ProtoMessage() {}

func (x *PutChunkResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_chunkstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutChunkResponse.ProtoReflect.Descriptor instead.
func (*PutChunkResponse) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_chunkstore_proto_rawDescGZIP(), []int{5}
}

func (x *PutChunkResponse) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

var File_snix_castore_protos_rpc_chunkstore_proto protoreflect.FileDescriptor

const file_snix_castore_protos_rpc_chunkstore_proto_rawDesc = "" +
	"\n" +
	"(snix/castore/protos/rpc_chunkstore.proto\x12\x0fsnix.castore.v1\"*\n" +
	"\x10StatChunkRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\"\x13\n" +
	"\x11StatChunkResponse\")\n" +
	"\x0fGetChunkRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\"&\n" +
	"\x10GetChunkResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"%\n" +
	"\x0fPutChunkRequest\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"*\n" +
	"\x10PutChunkResponse\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest2\x8d\x02\n" +
	"\x11ChunkStoreService\x12R\n" +
	"\tStatChunk\x12!.snix.castore.v1.StatChunkRequest\x1a\".snix.castore.v1.StatChunkResponse\x12Q\n" +
	"\bGetChunk\x12 .snix.castore.v1.GetChunkRequest\x1a!.snix.castore.v1.GetChunkResponse0\x01\x12Q\n" +
	"\bPutChunk\x12 .snix.castore.v1.PutChunkRequest\x1a!.snix.castore.v1.PutChunkResponse(\x01B\"Z snix.dev/castore/proto;castorev1b\x06proto3"

var (
	file_snix_castore_protos_rpc_chunkstore_proto_rawDescOnce sync.Once
	file_snix_castore_protos_rpc_chunkstore_proto_rawDescData []byte
)

func file_snix_castore_protos_rpc_chunkstore_proto_rawDescGZIP() []byte {
	file_snix_castore_protos_rpc_chunkstore_proto_rawDescOnce.Do(func() {
		file_snix_castore_protos_rpc_chunkstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snix_castore_protos_rpc_chunkstore_proto_rawDesc), len(file_snix_castore_protos_rpc_chunkstore_proto_rawDesc)))
	})
	return file_snix_castore_protos_rpc_chunkstore_proto_rawDescData
}

var file_snix_castore_protos_rpc_chunkstore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_snix_castore_protos_rpc_chunkstore_proto_goTypes = []any{
	(*StatChunkRequest)(nil),  // 0: snix.castore.v1.StatChunkRequest
	(*StatChunkResponse)(nil), // 1: snix.castore.v1.StatChunkResponse
	(*GetChunkRequest)(nil),   // 2: snix.castore.v1.GetChunkRequest
	(*GetChunkResponse)(nil),  // 3: snix.castore.v1.GetChunkResponse
	(*PutChunkRequest)(nil),   // 4: snix.castore.v1.PutChunkRequest
	(*PutChunkResponse)(nil),  // 5: snix.castore.v1.PutChunkResponse
}
var file_snix_castore_protos_rpc_chunkstore_proto_depIdxs = []int32{
	0, // 0: snix.castore.v1.ChunkStoreService.StatChunk:input_type -> snix.castore.v1.StatChunkRequest
	2, // 1: snix.castore.v1.ChunkStoreService.GetChunk:input_type -> snix.castore.v1.GetChunkRequest
	4, // 2: snix.castore.v1.ChunkStoreService.PutChunk:input_type -> snix.castore.v1.PutChunkRequest
	1, // 3: snix.castore.v1.ChunkStoreService.StatChunk:output_type -> snix.castore.v1.StatChunkResponse
	3, // 4: snix.castore.v1.ChunkStoreService.GetChunk:output_type -> snix.castore.v1.GetChunkResponse
	5, // 5: snix.castore.v1.ChunkStoreService.PutChunk:output_type -> snix.castore.v1.PutChunkResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_snix_castore_protos_rpc_chunkstore_proto_init() }
func file_snix_castore_protos_rpc_chunkstore_proto_init() {
	if File_snix_castore_protos_rpc_chunkstore_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snix_castore_protos_rpc_chunkstore_proto_rawDesc), len(file_snix_castore_protos_rpc_chunkstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snix_castore_protos_rpc_chunkstore_proto_goTypes,
		DependencyIndexes: file_snix_castore_protos_rpc_chunkstore_proto_depIdxs,
		MessageInfos:      file_snix_castore_protos_rpc_chunkstore_proto_msgTypes,
	}.Build()
	File_snix_castore_protos_rpc_chunkstore_proto = out.File
	file_snix_castore_protos_rpc_chunkstore_proto_goTypes = nil
	file_snix_castore_protos_rpc_chunkstore_proto_depIdxs = nil
}
