// SPDX-License-Identifier: MIT
// Copyright © 2026 The Snix Project

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: snix/castore/protos/rpc_blobstore.proto

package castorev1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BSStatBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The blake3 digest of the blob requested
	Digest        []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BSStatBlobRequest) Reset() {
	*x = BSStatBlobRequest{}
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BSStatBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSStatBlobRequest) ProtoMessage() {}

func (x *BSStatBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSStatBlobRequest.ProtoReflect.Descriptor instead.
func (*BSStatBlobRequest) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_blobstore_proto_rawDescGZIP(), []int{0}
}

func (x *BSStatBlobRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type BSStatBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BSStatBlobResponse) Reset() {
	*x = BSStatBlobResponse{}
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BSStatBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSStatBlobResponse) ProtoMessage() {}

func (x *BSStatBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSStatBlobResponse.ProtoReflect.Descriptor instead.
func (*BSStatBlobResponse) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_blobstore_proto_rawDescGZIP(), []int{1}
}

type GetBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The blake3 digest of the blob requested
	Digest        []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobRequest) Reset() {
	*x = GetBlobRequest{}
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobRequest) ProtoMessage() {}

func (x *GetBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobRequest.ProtoReflect.Descriptor instead.
func (*GetBlobRequest) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_blobstore_proto_rawDescGZIP(), []int{2}
}

func (x *GetBlobRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

type GetBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BlobMeta      *BlobMeta              `protobuf:"bytes,1,opt,name=blob_meta,json=blobMeta,proto3" json:"blob_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetBlobResponse) Reset() {
	*x = GetBlobResponse{}
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetBlobResponse) ProtoMessage() {}

func (x *GetBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetBlobResponse.ProtoReflect.Descriptor instead.
func (*GetBlobResponse) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_blobstore_proto_rawDescGZIP(), []int{3}
}

func (x *GetBlobResponse) GetBlobMeta() *BlobMeta {
	if x != nil {
		return x.BlobMeta
	}
	return nil
}

type PutBlobRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The blake3 digest of the blob uploaded
	Digest []byte `protobuf:"bytes,1,opt,name=digest,proto3" json:"digest,omitempty"`
	// Its BlobMeta
	BlobMeta      *BlobMeta `protobuf:"bytes,2,opt,name=blob_meta,json=blobMeta,proto3" json:"blob_meta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PutBlobRequest) Reset() {
	*x = PutBlobRequest{}
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PutBlobRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PutBlobRequest) ProtoMessage() {}

func (x *PutBlobRequest) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PutBlobRequest.ProtoReflect.Descriptor instead.
func (*PutBlobRequest) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_blobstore_proto_rawDescGZIP(), []int{4}
}

func (x *PutBlobRequest) GetDigest() []byte {
	if x != nil {
		return x.Digest
	}
	return nil
}

func (x *PutBlobRequest) GetBlobMeta() *BlobMeta {
	if x != nil {
		return x.BlobMeta
	}
	return nil
}

type BSPutBlobResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BSPutBlobResponse) Reset() {
	*x = BSPutBlobResponse{}
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BSPutBlobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BSPutBlobResponse) ProtoMessage() {}

func (x *BSPutBlobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_snix_castore_protos_rpc_blobstore_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BSPutBlobResponse.ProtoReflect.Descriptor instead.
func (*BSPutBlobResponse) Descriptor() ([]byte, []int) {
	return file_snix_castore_protos_rpc_blobstore_proto_rawDescGZIP(), []int{5}
}

var File_snix_castore_protos_rpc_blobstore_proto protoreflect.FileDescriptor

const file_snix_castore_protos_rpc_blobstore_proto_rawDesc = "" +
	"\n" +
	"'snix/castore/protos/rpc_blobstore.proto\x12\x0fsnix.castore.v1\x1a#snix/castore/protos/blobstore.proto\"+\n" +
	"\x11BSStatBlobRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\"\x14\n" +
	"\x12BSStatBlobResponse\"(\n" +
	"\x0eGetBlobRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\"I\n" +
	"\x0fGetBlobResponse\x126\n" +
	"\tblob_meta\x18\x01 \x01(\v2\x19.snix.castore.v1.BlobMetaR\bblobMeta\"`\n" +
	"\x0ePutBlobRequest\x12\x16\n" +
	"\x06digest\x18\x01 \x01(\fR\x06digest\x126\n" +
	"\tblob_meta\x18\x02 \x01(\v2\x19.snix.castore.v1.BlobMetaR\bblobMeta\"\x13\n" +
	"\x11BSPutBlobResponse2\x85\x02\n" +
	"\x10BlobStoreService\x12S\n" +
	"\bStatBlob\x12\".snix.castore.v1.BSStatBlobRequest\x1a#.snix.castore.v1.BSStatBlobResponse\x12L\n" +
	"\aGetBlob\x12\x1f.snix.castore.v1.GetBlobRequest\x1a .snix.castore.v1.GetBlobResponse\x12N\n" +
	"\aPutBlob\x12\x1f.snix.castore.v1.PutBlobRequest\x1a\".snix.castore.v1.BSPutBlobResponseB\"Z snix.dev/castore/proto;castorev1b\x06proto3"

var (
	file_snix_castore_protos_rpc_blobstore_proto_rawDescOnce sync.Once
	file_snix_castore_protos_rpc_blobstore_proto_rawDescData []byte
)

func file_snix_castore_protos_rpc_blobstore_proto_rawDescGZIP() []byte {
	file_snix_castore_protos_rpc_blobstore_proto_rawDescOnce.Do(func() {
		file_snix_castore_protos_rpc_blobstore_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_snix_castore_protos_rpc_blobstore_proto_rawDesc), len(file_snix_castore_protos_rpc_blobstore_proto_rawDesc)))
	})
	return file_snix_castore_protos_rpc_blobstore_proto_rawDescData
}

var file_snix_castore_protos_rpc_blobstore_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_snix_castore_protos_rpc_blobstore_proto_goTypes = []any{
	(*BSStatBlobRequest)(nil),  // 0: snix.castore.v1.BSStatBlobRequest
	(*BSStatBlobResponse)(nil), // 1: snix.castore.v1.BSStatBlobResponse
	(*GetBlobRequest)(nil),     // 2: snix.castore.v1.GetBlobRequest
	(*GetBlobResponse)(nil),    // 3: snix.castore.v1.GetBlobResponse
	(*PutBlobRequest)(nil),     // 4: snix.castore.v1.PutBlobRequest
	(*BSPutBlobResponse)(nil),  // 5: snix.castore.v1.BSPutBlobResponse
	(*BlobMeta)(nil),           // 6: snix.castore.v1.BlobMeta
}
var file_snix_castore_protos_rpc_blobstore_proto_depIdxs = []int32{
	6, // 0: snix.castore.v1.GetBlobResponse.blob_meta:type_name -> snix.castore.v1.BlobMeta
	6, // 1: snix.castore.v1.PutBlobRequest.blob_meta:type_name -> snix.castore.v1.BlobMeta
	0, // 2: snix.castore.v1.BlobStoreService.StatBlob:input_type -> snix.castore.v1.BSStatBlobRequest
	2, // 3: snix.castore.v1.BlobStoreService.GetBlob:input_type -> snix.castore.v1.GetBlobRequest
	4, // 4: snix.castore.v1.BlobStoreService.PutBlob:input_type -> snix.castore.v1.PutBlobRequest
	1, // 5: snix.castore.v1.BlobStoreService.StatBlob:output_type -> snix.castore.v1.BSStatBlobResponse
	3, // 6: snix.castore.v1.BlobStoreService.GetBlob:output_type -> snix.castore.v1.GetBlobResponse
	5, // 7: snix.castore.v1.BlobStoreService.PutBlob:output_type -> snix.castore.v1.BSPutBlobResponse
	5, // [5:8] is the sub-list for method output_type
	2, // [2:5] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_snix_castore_protos_rpc_blobstore_proto_init() }
func file_snix_castore_protos_rpc_blobstore_proto_init() {
	if File_snix_castore_protos_rpc_blobstore_proto != nil {
		return
	}
	file_snix_castore_protos_blobstore_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_snix_castore_protos_rpc_blobstore_proto_rawDesc), len(file_snix_castore_protos_rpc_blobstore_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_snix_castore_protos_rpc_blobstore_proto_goTypes,
		DependencyIndexes: file_snix_castore_protos_rpc_blobstore_proto_depIdxs,
		MessageInfos:      file_snix_castore_protos_rpc_blobstore_proto_msgTypes,
	}.Build()
	File_snix_castore_protos_rpc_blobstore_proto = out.File
	file_snix_castore_protos_rpc_blobstore_proto_goTypes = nil
	file_snix_castore_protos_rpc_blobstore_proto_depIdxs = nil
}
