// SPDX-License-Identifier: MIT
// Copyright © 2026 The Snix Project

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: snix/castore/protos/rpc_chunkstore.proto

package castorev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ChunkStoreService_StatChunk_FullMethodName = "/snix.castore.v1.ChunkStoreService/StatChunk"
	ChunkStoreService_GetChunk_FullMethodName  = "/snix.castore.v1.ChunkStoreService/GetChunk"
	ChunkStoreService_PutChunk_FullMethodName  = "/snix.castore.v1.ChunkStoreService/PutChunk"
)

// ChunkStoreServiceClient is the client API for ChunkStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// ChunkStoreService allows reading (or uploading) content-addressed chunks of raw data.
// BLAKE3 is used as a hashing function for the data. Uploading a blob will
// return the BLAKE3 digest of it, and that's the identifier used to Read/Stat
// them too.
// Chunks are considered small enough to not require any further chunking,
// but may be broken down into smaller messages when sent as proto messages,
// due to message size restrictions.
type ChunkStoreServiceClient interface {
	// Stat can be used to check for the existence of a chunk.
	StatChunk(ctx context.Context, in *StatChunkRequest, opts ...grpc.CallOption) (*StatChunkResponse, error)
	// Get can be used to retrieve a chunk.
	// The server may break down the response into a stream of smaller messages,
	// to keep proto messages smaller than its maximum chunk size.
	GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChunkResponse], error)
	// PutChunk can be used to upload a chunk.
	// The client may break down the response into a stream of smaller messages,
	// to keep proto messages smaller than its maximum chunk size.
	PutChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutChunkRequest, PutChunkResponse], error)
}

type chunkStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChunkStoreServiceClient(cc grpc.ClientConnInterface) ChunkStoreServiceClient {
	return &chunkStoreServiceClient{cc}
}

func (c *chunkStoreServiceClient) StatChunk(ctx context.Context, in *StatChunkRequest, opts ...grpc.CallOption) (*StatChunkResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatChunkResponse)
	err := c.cc.Invoke(ctx, ChunkStoreService_StatChunk_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chunkStoreServiceClient) GetChunk(ctx context.Context, in *GetChunkRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkStoreService_ServiceDesc.Streams[0], ChunkStoreService_GetChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetChunkRequest, GetChunkResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkStoreService_GetChunkClient = grpc.ServerStreamingClient[GetChunkResponse]

func (c *chunkStoreServiceClient) PutChunk(ctx context.Context, opts ...grpc.CallOption) (grpc.ClientStreamingClient[PutChunkRequest, PutChunkResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &ChunkStoreService_ServiceDesc.Streams[1], ChunkStoreService_PutChunk_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[PutChunkRequest, PutChunkResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkStoreService_PutChunkClient = grpc.ClientStreamingClient[PutChunkRequest, PutChunkResponse]

// ChunkStoreServiceServer is the server API for ChunkStoreService service.
// All implementations must embed UnimplementedChunkStoreServiceServer
// for forward compatibility.
//
// ChunkStoreService allows reading (or uploading) content-addressed chunks of raw data.
// BLAKE3 is used as a hashing function for the data. Uploading a blob will
// return the BLAKE3 digest of it, and that's the identifier used to Read/Stat
// them too.
// Chunks are considered small enough to not require any further chunking,
// but may be broken down into smaller messages when sent as proto messages,
// due to message size restrictions.
type ChunkStoreServiceServer interface {
	// Stat can be used to check for the existence of a chunk.
	StatChunk(context.Context, *StatChunkRequest) (*StatChunkResponse, error)
	// Get can be used to retrieve a chunk.
	// The server may break down the response into a stream of smaller messages,
	// to keep proto messages smaller than its maximum chunk size.
	GetChunk(*GetChunkRequest, grpc.ServerStreamingServer[GetChunkResponse]) error
	// PutChunk can be used to upload a chunk.
	// The client may break down the response into a stream of smaller messages,
	// to keep proto messages smaller than its maximum chunk size.
	PutChunk(grpc.ClientStreamingServer[PutChunkRequest, PutChunkResponse]) error
	mustEmbedUnimplementedChunkStoreServiceServer()
}

// UnimplementedChunkStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedChunkStoreServiceServer struct{}

func (UnimplementedChunkStoreServiceServer) StatChunk(context.Context, *StatChunkRequest) (*StatChunkResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StatChunk not implemented")
}
func (UnimplementedChunkStoreServiceServer) GetChunk(*GetChunkRequest, grpc.ServerStreamingServer[GetChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method GetChunk not implemented")
}
func (UnimplementedChunkStoreServiceServer) PutChunk(grpc.ClientStreamingServer[PutChunkRequest, PutChunkResponse]) error {
	return status.Error(codes.Unimplemented, "method PutChunk not implemented")
}
func (UnimplementedChunkStoreServiceServer) mustEmbedUnimplementedChunkStoreServiceServer() {}
func (UnimplementedChunkStoreServiceServer) testEmbeddedByValue()                           {}

// UnsafeChunkStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChunkStoreServiceServer will
// result in compilation errors.
type UnsafeChunkStoreServiceServer interface {
	mustEmbedUnimplementedChunkStoreServiceServer()
}

func RegisterChunkStoreServiceServer(s grpc.ServiceRegistrar, srv ChunkStoreServiceServer) {
	// If the following call panics, it indicates UnimplementedChunkStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ChunkStoreService_ServiceDesc, srv)
}

func _ChunkStoreService_StatChunk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatChunkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChunkStoreServiceServer).StatChunk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ChunkStoreService_StatChunk_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChunkStoreServiceServer).StatChunk(ctx, req.(*StatChunkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChunkStoreService_GetChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetChunkRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChunkStoreServiceServer).GetChunk(m, &grpc.GenericServerStream[GetChunkRequest, GetChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkStoreService_GetChunkServer = grpc.ServerStreamingServer[GetChunkResponse]

func _ChunkStoreService_PutChunk_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChunkStoreServiceServer).PutChunk(&grpc.GenericServerStream[PutChunkRequest, PutChunkResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type ChunkStoreService_PutChunkServer = grpc.ClientStreamingServer[PutChunkRequest, PutChunkResponse]

// ChunkStoreService_ServiceDesc is the grpc.ServiceDesc for ChunkStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChunkStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snix.castore.v1.ChunkStoreService",
	HandlerType: (*ChunkStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StatChunk",
			Handler:    _ChunkStoreService_StatChunk_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetChunk",
			Handler:       _ChunkStoreService_GetChunk_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "PutChunk",
			Handler:       _ChunkStoreService_PutChunk_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "snix/castore/protos/rpc_chunkstore.proto",
}
