// SPDX-License-Identifier: MIT
// Copyright © 2026 The Snix Project

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: snix/castore/protos/rpc_blobstore.proto

package castorev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	BlobStoreService_StatBlob_FullMethodName = "/snix.castore.v1.BlobStoreService/StatBlob"
	BlobStoreService_GetBlob_FullMethodName  = "/snix.castore.v1.BlobStoreService/GetBlob"
	BlobStoreService_PutBlob_FullMethodName  = "/snix.castore.v1.BlobStoreService/PutBlob"
)

// BlobStoreServiceClient is the client API for BlobStoreService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// BlobStoreService retrieves and stores metadata about blobs.
// Blobs can consist of multiple chunks.
// The stored metadata describes which chunks need to be assembled
// to produce the entire blob contents.
// Blobs are keyed by the BLAKE3 digest of their entire data
type BlobStoreServiceClient interface {
	// Stat checks if a [BlobMeta] for a given blob exists.
	StatBlob(ctx context.Context, in *BSStatBlobRequest, opts ...grpc.CallOption) (*BSStatBlobResponse, error)
	// Get retrieves a [BlobMeta] for a given blob digest.
	GetBlob(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (*GetBlobResponse, error)
	// Put persists a [BlobMeta] for the given blob digest.
	PutBlob(ctx context.Context, in *PutBlobRequest, opts ...grpc.CallOption) (*BSPutBlobResponse, error)
}

type blobStoreServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewBlobStoreServiceClient(cc grpc.ClientConnInterface) BlobStoreServiceClient {
	return &blobStoreServiceClient{cc}
}

func (c *blobStoreServiceClient) StatBlob(ctx context.Context, in *BSStatBlobRequest, opts ...grpc.CallOption) (*BSStatBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BSStatBlobResponse)
	err := c.cc.Invoke(ctx, BlobStoreService_StatBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobStoreServiceClient) GetBlob(ctx context.Context, in *GetBlobRequest, opts ...grpc.CallOption) (*GetBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBlobResponse)
	err := c.cc.Invoke(ctx, BlobStoreService_GetBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *blobStoreServiceClient) PutBlob(ctx context.Context, in *PutBlobRequest, opts ...grpc.CallOption) (*BSPutBlobResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BSPutBlobResponse)
	err := c.cc.Invoke(ctx, BlobStoreService_PutBlob_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// BlobStoreServiceServer is the server API for BlobStoreService service.
// All implementations must embed UnimplementedBlobStoreServiceServer
// for forward compatibility.
//
// BlobStoreService retrieves and stores metadata about blobs.
// Blobs can consist of multiple chunks.
// The stored metadata describes which chunks need to be assembled
// to produce the entire blob contents.
// Blobs are keyed by the BLAKE3 digest of their entire data
type BlobStoreServiceServer interface {
	// Stat checks if a [BlobMeta] for a given blob exists.
	StatBlob(context.Context, *BSStatBlobRequest) (*BSStatBlobResponse, error)
	// Get retrieves a [BlobMeta] for a given blob digest.
	GetBlob(context.Context, *GetBlobRequest) (*GetBlobResponse, error)
	// Put persists a [BlobMeta] for the given blob digest.
	PutBlob(context.Context, *PutBlobRequest) (*BSPutBlobResponse, error)
	mustEmbedUnimplementedBlobStoreServiceServer()
}

// UnimplementedBlobStoreServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedBlobStoreServiceServer struct{}

func (UnimplementedBlobStoreServiceServer) StatBlob(context.Context, *BSStatBlobRequest) (*BSStatBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StatBlob not implemented")
}
func (UnimplementedBlobStoreServiceServer) GetBlob(context.Context, *GetBlobRequest) (*GetBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBlob not implemented")
}
func (UnimplementedBlobStoreServiceServer) PutBlob(context.Context, *PutBlobRequest) (*BSPutBlobResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method PutBlob not implemented")
}
func (UnimplementedBlobStoreServiceServer) mustEmbedUnimplementedBlobStoreServiceServer() {}
func (UnimplementedBlobStoreServiceServer) testEmbeddedByValue()                          {}

// UnsafeBlobStoreServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to BlobStoreServiceServer will
// result in compilation errors.
type UnsafeBlobStoreServiceServer interface {
	mustEmbedUnimplementedBlobStoreServiceServer()
}

func RegisterBlobStoreServiceServer(s grpc.ServiceRegistrar, srv BlobStoreServiceServer) {
	// If the following call panics, it indicates UnimplementedBlobStoreServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&BlobStoreService_ServiceDesc, srv)
}

func _BlobStoreService_StatBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BSStatBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobStoreServiceServer).StatBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobStoreService_StatBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobStoreServiceServer).StatBlob(ctx, req.(*BSStatBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobStoreService_GetBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobStoreServiceServer).GetBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobStoreService_GetBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobStoreServiceServer).GetBlob(ctx, req.(*GetBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _BlobStoreService_PutBlob_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutBlobRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlobStoreServiceServer).PutBlob(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: BlobStoreService_PutBlob_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlobStoreServiceServer).PutBlob(ctx, req.(*PutBlobRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// BlobStoreService_ServiceDesc is the grpc.ServiceDesc for BlobStoreService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var BlobStoreService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "snix.castore.v1.BlobStoreService",
	HandlerType: (*BlobStoreServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StatBlob",
			Handler:    _BlobStoreService_StatBlob_Handler,
		},
		{
			MethodName: "GetBlob",
			Handler:    _BlobStoreService_GetBlob_Handler,
		},
		{
			MethodName: "PutBlob",
			Handler:    _BlobStoreService_PutBlob_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "snix/castore/protos/rpc_blobstore.proto",
}
